version: '3'
services:
  mongodb:
    image: 'mongo'
    container_name: 'mongodb'
    ports:
      - 27017:27017

  elastic:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.8.1"
    container_name: "elastic"
    environment: 
     - discovery.type=single-node
    ports:
     - 9200:9200
     - 9300:9300

  kibana:
    image: "docker.elastic.co/kibana/kibana:7.8.1"
    container_name: "kibana"
    links:
      - "elastic:elasticsearch"
    ports:
      - 5601:5601

  apm:
    image: "docker.elastic.co/apm/apm-server:7.8.1"
    container_name: "apm"
    links:
      - "elastic:elasticsearch"
    ports:
      - 8200:8200
    volumes:
      - ./apm-server.docker.yml:/usr/share/apm-server/apm-server.yml:ro
    command: >
      apm-server -e 
        -E output.elasticsearch.hosts=["elasticsearch:9200"]

